name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" # runs every 12 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Colorful Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: Kianis534
          outputs: |
            output/github-contribution-grid-snake-bright.svg?palette=#FF6B6B,#FFD93D,#6BCB77,#4D96FF,#FF6BFF

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
